name: Run Telegram Stock Bot

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: "0 0 * * *"   # setiap hari jam 07:00 WIB (karena UTC+0)
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci   # lebih cepat dan konsisten daripada npm install

      - name: Run bot script
        env:
            TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
            CHAT_ID: ${{ secrets.CHAT_ID }}
            GROUP_ID: ${{ secrets.GROUP_ID }}
            TOPIC_ID: ${{ secrets.TOPIC_ID }}
        run: node index.js
