name: Run Telegram Stock Bot

on:
  push:
    branches: [ "main" ]   # jalan otomatis tiap push ke branch main
  pull_request:
    branches: [ "main" ]   # juga jalan saat ada PR ke main
  workflow_dispatch:        # bisa dijalankan manual dari tab Actions

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'
          cache: 'npm'               # caching dependencies
          cache-dependency-path: '**/package-lock.json'

      - name: Install dependencies
        run: npm install

      - name: Run bot script
        run: node index.js